version: '3.8'

services:
  app_1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app_1
    depends_on:
      - db
      - load_balancer
    environment:
      - DB_URL=mysql+pymysql://user:password@db/dbname
      - PORT=8000
      - SERVICE_NAME=fastapi_app_1
      - TES_URL=third_party_service:8080
      - LOAD_BALANCER_URL=load_balancer:8000

    ports:
      - "8000:8000"
    networks:
      - my_network
  app_2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app_2
    depends_on:
      - db
      - load_balancer
    environment:
      - DB_URL=mysql+pymysql://user:password@db/dbname
      - PORT=8001
      - SERVICE_NAME=fastapi_app_2
      - TES_URL=third_party_service:8080
      - LOAD_BALANCER_URL=load_balancer:8000
    ports:
      - "8001:8000"
    networks:
      - my_network
  load_balancer:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    container_name: load_balancer
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8000"
    networks:
      - my_network
    depends_on:
      - redis
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  third_party_service:
    image: igorsakhankov/harbour-cloudcomputing
    container_name: third_party_service
    ports:
      - "8181:8080"
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
